export {
  Skeleton,
  PageSkeleton,
  LandingSkeleton,
  ApplyFormSkeleton,
  PanelFormSkeleton,
  TableSkeleton,
  FormSkeleton,
  StatsSkeleton,
  MediaGridSkeleton,
  ChartSkeleton,
  CmsSkeleton,
  AdminBootSkeleton,
  LoginSkeleton,
} from "./Skeleton";
